// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMIhw9kd2L3dEOvIiV1CdIq4P30M-FEcM',
    appId: '1:707486167483:web:fa8fa60024c4320bbf949e',
    messagingSenderId: '707486167483',
    projectId: 'eduapp-7adfc',
    authDomain: 'eduapp-7adfc.firebaseapp.com',
    storageBucket: 'eduapp-7adfc.appspot.com',
    measurementId: 'G-SZL7GQ076Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQx3J7D3ZkKMtLM-f8NGDNo-sn1UpfkIM',
    appId: '1:707486167483:android:88f0bd9c37c3019fbf949e',
    messagingSenderId: '707486167483',
    projectId: 'eduapp-7adfc',
    storageBucket: 'eduapp-7adfc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy2-2oCTmHABvTNgzjAv9gKDPq5C6IS0I',
    appId: '1:707486167483:ios:a714674d4b9e0251bf949e',
    messagingSenderId: '707486167483',
    projectId: 'eduapp-7adfc',
    storageBucket: 'eduapp-7adfc.appspot.com',
    androidClientId: '707486167483-rlq6e2hh7rh63bifjh7n2jku40hck36v.apps.googleusercontent.com',
    iosClientId: '707486167483-qam3gqj0au5pkk88ll501vnuptt9i5lf.apps.googleusercontent.com',
    iosBundleId: 'com.example.eduapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCy2-2oCTmHABvTNgzjAv9gKDPq5C6IS0I',
    appId: '1:707486167483:ios:a714674d4b9e0251bf949e',
    messagingSenderId: '707486167483',
    projectId: 'eduapp-7adfc',
    storageBucket: 'eduapp-7adfc.appspot.com',
    androidClientId: '707486167483-rlq6e2hh7rh63bifjh7n2jku40hck36v.apps.googleusercontent.com',
    iosClientId: '707486167483-qam3gqj0au5pkk88ll501vnuptt9i5lf.apps.googleusercontent.com',
    iosBundleId: 'com.example.eduapp',
  );
}
